### ISSUE TITLE
Broker sends error response on incorrectly encoded cmds from Client API

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda-zeebe/zeebe#107]
Example: Stream processor encounters a command from client api which is invalid (example: does not correspond to the expected structure, unsupported event type, required property missing ...)

In such cases, an error response is sent to the Client.

**Comment by Zelldon** [comment]
Please remove the TODO flag https://github.com/camunda-zeebe/zeebe/commit/1142d7dd2acf23d251ebfb307695379f8ffcb2b9#diff-6ed7baa858ee4574da927b3648f30f00R96

**Comment by meyerdan** [comment]
@saig0 @menski just stumbled upon
d7bfdcb while reading the code in ClientApiMessageHandler. I would like to have a brief chat about that today if possible
