### ISSUE TITLE
Confused about event types

### ISSUE THREAD

**Issue by berndruecker** [camunda-zeebe/zeebe#365]
When I log the events via the sample Event Logger I get the following info:

```
>>> [topic: 0, position: 4294980104, key: 4294980104, type: **WORKFLOW_INSTANCE**]
{"eventType":"**ACTIVITY_READY**","bpmnProcessId":"demoProcess","workflowInstanceKey":4294979128,"activityId":"taskA","version":1,"payload":"gaFhoWI="}
===
>>> [topic: 0, position: 4294980344, key: 4294980104, type: **WORKFLOW_INSTANCE**]
{"eventType":"**ACTIVITY_ACTIVATED**","bpmnProcessId":"demoProcess","workflowInstanceKey":4294979128,"activityId":"taskA","version":1,"payload":"gaNmb2+hYg=="}
===
>>> [topic: 0, position: 4294980592, key: 4294980592, type: **TASK**]
{"eventType":"**CREATE**","lockTime":-9223372036854775808,"lockOwner":"","retries":3,"type":"foo","headers":{"bpmnProcessId":"demoProcess","workflowDefinitionVersion":1,"workflowInstanceKey":4294979128,"activityId":"taskA","activityInstanceKey":4294980104,"customHeaders":[]},"payload":"gaNmb2+hYg=="}
===
>>> [topic: 0, position: 4294980944, key: 4294980592, type: **TASK**]
{"eventType":"**CREATED**","lockTime":-9223372036854775808,"lockOwner":"","retries":3,"type":"foo","headers":{"bpmnProcessId":"demoProcess","workflowDefinitionVersion":1,"workflowInstanceKey":4294979128,"activityId":"taskA","activityInstanceKey":4294980104,"customHeaders":[]},"payload":"gaNmb2+hYg=="}
===
```

I struggle with the mapping of eventType from JSON to the EventMetadata. How is this done?
What is the meaning of the different event types? How can I read more details if not from the Metadata - do I have to read the JSON directly? Why then the metadata class?

Unfortunately there is no Apidoc available to get some more insides.

**Comment by meyerdan** [comment]
Hi Bernd,

Hey cool, you tried the example code :)

What do you mean with this sentence:
> I struggle with the mapping of eventType from JSON to the EventMetadata. How is this done?

In the stream you have WORKFLOW_INSTANCE and TASK events.

**Comment by berndruecker** [comment]
I even try to update my monitoring tool to read the new stream :-)

Why is there a different type in the JSON data: **"eventType":"ACTIVITY_READY"**?
Why can't I get this from the metadata object? And worse: Why is this also called eventType but has a different value than `meta.getEventType()`
Is there a constant class for these event types? Or some overview which I can expect?

**Comment by berndruecker** [comment]
Daniel just told me the client API will change fundamentally, so I wait for this to happen and try it again with the next version
